/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ArmAutosendRequest, ArmAutosendResult, EmailProviderPreset, EmailStatusResult, EmailSummarySettings, SendEmailRequest, SendEmailResult } from '@deepseek-ai/dsh-email-summary/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$656d61696c53756d6d617279 {
    armAutosend: (request: ArmAutosendRequest) => Promise<RemoteResult<ArmAutosendResult>>
    getSettings: () => Promise<RemoteResult<{ settings: EmailSummarySettings; presets: EmailProviderPreset[]; configured: boolean; }>>
    saveSettings: (request: { patch: Partial<EmailSummarySettings>; }) => Promise<RemoteResult<{ ok: boolean; error?: string; }>>
    sendNow: (request: SendEmailRequest) => Promise<RemoteResult<SendEmailResult>>
    setPassword: (request: { password: string; }) => Promise<RemoteResult<{ ok: boolean; error?: string; }>>
    status: (request: { sessionId: SessionId; }) => Promise<RemoteResult<EmailStatusResult>>
  }
  interface TypertRemoteMap {
    'emailSummary/armAutosend': (request: ArmAutosendRequest) => Promise<RemoteResult<ArmAutosendResult>>
    'emailSummary/getSettings': () => Promise<RemoteResult<{ settings: EmailSummarySettings; presets: EmailProviderPreset[]; configured: boolean; }>>
    'emailSummary/saveSettings': (request: { patch: Partial<EmailSummarySettings>; }) => Promise<RemoteResult<{ ok: boolean; error?: string; }>>
    'emailSummary/sendNow': (request: SendEmailRequest) => Promise<RemoteResult<SendEmailResult>>
    'emailSummary/setPassword': (request: { password: string; }) => Promise<RemoteResult<{ ok: boolean; error?: string; }>>
    'emailSummary/status': (request: { sessionId: SessionId; }) => Promise<RemoteResult<EmailStatusResult>>
  }
  interface TypertRemoteNamespaceMap {
    'emailSummary': TypertRemoteNamespace$656d61696c53756d6d617279
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
