/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_email_summary_emailSummary_armAutosend_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
  'enabled': z.boolean(),
  'recipient': z.string().optional(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_armAutosend_result$schema = z.object({
  'ok': z.boolean(),
  'armed': z.boolean(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_getSettings_result$schema = z.object({
  'settings': z.object({
  'provider': z.string(),
  'smtpHost': z.string(),
  'smtpPort': z.number(),
  'secure': z.string(),
  'username': z.string(),
  'from': z.string(),
  'defaultRecipient': z.string(),
  'style': z.string(),
  'prompt': z.string(),
  'reportEnabled': z.boolean(),
  'reportFrequency': z.string(),
  'reportTime': z.string(),
  'reportWeekday': z.number(),
}),
  'presets': z.array(z.object({
  'id': z.union([z.literal("gmail"), z.literal("qq"), z.literal("163"), z.literal("126"), z.literal("outlook"), z.literal("custom")]),
  'label': z.string(),
  'host': z.string(),
  'port': z.number(),
  'secure': z.union([z.literal("starttls"), z.literal("ssl"), z.literal("none")]),
})),
  'configured': z.boolean(),
  'defaultPrompts': z.object({
  'brief': z.string(),
  'detailed': z.string(),
}),
})
const _deepseek_ai_dsh_email_summary_emailSummary_saveSettings_parameter_0$schema = z.object({
  'patch': z.object({
  'provider': z.string().optional(),
  'smtpHost': z.string().optional(),
  'smtpPort': z.number().optional(),
  'secure': z.string().optional(),
  'username': z.string().optional(),
  'from': z.string().optional(),
  'defaultRecipient': z.string().optional(),
  'style': z.string().optional(),
  'prompt': z.string().optional(),
  'reportEnabled': z.boolean().optional(),
  'reportFrequency': z.string().optional(),
  'reportTime': z.string().optional(),
  'reportWeekday': z.number().optional(),
}),
})
const _deepseek_ai_dsh_email_summary_emailSummary_saveSettings_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_sendNow_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
  'recipient': z.string().optional(),
  'subject': z.string().optional(),
  'style': z.union([z.literal("brief"), z.literal("detailed")]).optional(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_sendNow_result$schema = z.object({
  'ok': z.boolean(),
  'recipient': z.string(),
  'subject': z.string(),
  'summaryChars': z.number(),
  'transcriptChars': z.number(),
  'summary': z.string().optional(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_setPassword_parameter_0$schema = z.object({
  'password': z.string(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_setPassword_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_email_summary_emailSummary_status_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
})
const _deepseek_ai_dsh_email_summary_emailSummary_status_result$schema = z.object({
  'configured': z.boolean(),
  'defaultRecipient': z.string(),
  'armed': z.boolean(),
  'presets': z.array(z.object({
  'id': z.union([z.literal("gmail"), z.literal("qq"), z.literal("163"), z.literal("126"), z.literal("outlook"), z.literal("custom")]),
  'label': z.string(),
  'host': z.string(),
  'port': z.number(),
  'secure': z.union([z.literal("starttls"), z.literal("ssl"), z.literal("none")]),
})),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-email-summary',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-email-summary#emailSummary/armAutosend',
      service: 'emailSummary',
      namespace: 'emailSummary',
      method: 'armAutosend',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-email-summary/types#ArmAutosendRequest',
            schema: _deepseek_ai_dsh_email_summary_emailSummary_armAutosend_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-email-summary/types#ArmAutosendResult',
        schema: _deepseek_ai_dsh_email_summary_emailSummary_armAutosend_result$schema,
      },
      sourceLocation: {"file":"packages/notification/email-summary/src/index.ts","line":311,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-email-summary#emailSummary/getSettings',
      service: 'emailSummary',
      namespace: 'emailSummary',
      method: 'getSettings',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-email-summary#emailSummary/getSettings:result',
        schema: _deepseek_ai_dsh_email_summary_emailSummary_getSettings_result$schema,
      },
      sourceLocation: {"file":"packages/notification/email-summary/src/index.ts","line":334,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-email-summary#emailSummary/saveSettings',
      service: 'emailSummary',
      namespace: 'emailSummary',
      method: 'saveSettings',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-email-summary#emailSummary/saveSettings:request',
            schema: _deepseek_ai_dsh_email_summary_emailSummary_saveSettings_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-email-summary#emailSummary/saveSettings:result',
        schema: _deepseek_ai_dsh_email_summary_emailSummary_saveSettings_result$schema,
      },
      sourceLocation: {"file":"packages/notification/email-summary/src/index.ts","line":350,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-email-summary#emailSummary/sendNow',
      service: 'emailSummary',
      namespace: 'emailSummary',
      method: 'sendNow',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-email-summary/types#SendEmailRequest',
            schema: _deepseek_ai_dsh_email_summary_emailSummary_sendNow_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-email-summary/types#SendEmailResult',
        schema: _deepseek_ai_dsh_email_summary_emailSummary_sendNow_result$schema,
      },
      sourceLocation: {"file":"packages/notification/email-summary/src/index.ts","line":294,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-email-summary#emailSummary/setPassword',
      service: 'emailSummary',
      namespace: 'emailSummary',
      method: 'setPassword',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-email-summary#emailSummary/setPassword:request',
            schema: _deepseek_ai_dsh_email_summary_emailSummary_setPassword_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-email-summary#emailSummary/setPassword:result',
        schema: _deepseek_ai_dsh_email_summary_emailSummary_setPassword_result$schema,
      },
      sourceLocation: {"file":"packages/notification/email-summary/src/index.ts","line":364,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-email-summary#emailSummary/status',
      service: 'emailSummary',
      namespace: 'emailSummary',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-email-summary#emailSummary/status:request',
            schema: _deepseek_ai_dsh_email_summary_emailSummary_status_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-email-summary/types#EmailStatusResult',
        schema: _deepseek_ai_dsh_email_summary_emailSummary_status_result$schema,
      },
      sourceLocation: {"file":"packages/notification/email-summary/src/index.ts","line":322,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service for conversation summarization + SMTP delivery.",
        "summary": "Host service for conversation summarization + SMTP delivery.",
        "tags": [],
        "jsDoc": "/** Host service for conversation summarization + SMTP delivery. */",
        "key": "emailSummary",
        "exportName": "EmailSummaryService",
        "members": [
          {
            "kind": "method",
            "name": "sendNow",
            "signature": "@Remote('sendNow') async sendNow(request: SendEmailRequest): Promise<SendEmailResult>",
            "summary": "Summarize the current conversation and email it now.",
            "jsDoc": "/** Summarize the current conversation and email it now. */"
          },
          {
            "kind": "method",
            "name": "armAutosend",
            "signature": "@Remote('armAutosend') armAutosend(request: ArmAutosendRequest): ArmAutosendResult",
            "summary": "Arm or disarm auto-send for one conversation.",
            "jsDoc": "/** Arm or disarm auto-send for one conversation. */"
          },
          {
            "kind": "method",
            "name": "status",
            "signature": "@Remote('status') async status(request: { sessionId: SessionId }): Promise<EmailStatusResult>",
            "summary": "Read configuration + armed state for the settings surface and toggles.",
            "jsDoc": "/** Read configuration + armed state for the settings surface and toggles. */"
          },
          {
            "kind": "method",
            "name": "getSettings",
            "signature": "@Remote('getSettings') async getSettings(): Promise<{ settings: EmailSummarySettings; presets: EmailProviderPreset[]; configured: boolean; defaultPrompts: { brief: string; detailed: string } }>",
            "summary": "Read the raw persisted settings (the surface edits these).",
            "jsDoc": "/** Read the raw persisted settings (the surface edits these). */"
          },
          {
            "kind": "method",
            "name": "saveSettings",
            "signature": "@Remote('saveSettings') async saveSettings(request: { patch: Partial<EmailSummarySettings> }): Promise<{ ok: boolean; error?: string }>",
            "summary": "Persist a partial settings patch.",
            "jsDoc": "/** Persist a partial settings patch. */"
          },
          {
            "kind": "method",
            "name": "setPassword",
            "signature": "@Remote('setPassword') async setPassword(request: { password: string }): Promise<{ ok: boolean; error?: string }>",
            "summary": "Store (or clear) the SMTP password through the credential seam.",
            "jsDoc": "/** Store (or clear) the SMTP password through the credential seam. */"
          }
        ],
        "types": [
          {
            "name": "ArmAutosendRequest",
            "declaration": "export interface ArmAutosendRequest {\n    sessionId: SessionId;\n    enabled: boolean;\n    recipient?: string;\n}"
          },
          {
            "name": "ArmAutosendResult",
            "declaration": "export interface ArmAutosendResult {\n    ok: boolean;\n    armed: boolean;\n}"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "EmailProviderId",
            "declaration": "export type EmailProviderId = 'gmail' | 'qq' | '163' | '126' | 'outlook' | 'custom';"
          },
          {
            "name": "EmailProviderPreset",
            "declaration": "export interface EmailProviderPreset {\n    id: EmailProviderId;\n    label: string;\n    host: string;\n    port: number;\n    secure: EmailSecureMode;\n}"
          },
          {
            "name": "EmailSecureMode",
            "declaration": "export type EmailSecureMode = 'starttls' | 'ssl' | 'none';"
          },
          {
            "name": "EmailStatusResult",
            "declaration": "export interface EmailStatusResult {\n    configured: boolean;\n    defaultRecipient: string;\n    armed: boolean;\n    presets: EmailProviderPreset[];\n}"
          },
          {
            "name": "EmailSummarySettings",
            "declaration": "export interface EmailSummarySettings {\n    provider: string;\n    smtpHost: string;\n    smtpPort: number;\n    secure: string;\n    username: string;\n    from: string;\n    defaultRecipient: string;\n    style: string;\n    prompt: string;\n    reportEnabled: boolean;\n    reportFrequency: string;\n    reportTime: string;\n    reportWeekday: number;\n}"
          },
          {
            "name": "EmailSummaryStyle",
            "declaration": "export type EmailSummaryStyle = 'brief' | 'detailed';"
          },
          {
            "name": "SendEmailRequest",
            "declaration": "export interface SendEmailRequest {\n    sessionId: SessionId;\n    recipient?: string;\n    subject?: string;\n    style?: EmailSummaryStyle;\n}"
          },
          {
            "name": "SendEmailResult",
            "declaration": "export interface SendEmailResult {\n    ok: boolean;\n    recipient: string;\n    subject: string;\n    summaryChars: number;\n    transcriptChars: number;\n    summary?: string;\n    error?: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
